### ISSUE TITLE
[Server thread/ERROR] [Sponge]: The Scheduler tried to run the task noteblockapi-S-305 owned by Plugin{id=noteblockapi

### ISSUE THREAD

**Issue by ziceptor** [clienthax/MusicBox#4]
The chest with discs + jukebox. http://pastebin.com/JpmdXTu5

forge-1.10.2-12.18.2.2123-universal.jar
spongeforge-1.10.2-2123-5.1.0-BETA-1888.jar
noteblockapi-2.1.jar
musicbox-0.41.jar

**Comment by clienthax** [comment]
Il look into this soon, looks like sponge changed the api again

**Comment by clienthax** [comment]
Fixed in latest api.
